:PROPERTIES:
:ID:       D5951A75-FCE5-44D6-A820-A0257E70BCC4
:END:

#+title: IFS
Tags: [[id:a8290213-3af8-4c76-b6a1-01a7a7af5fe3][Dario Martinez]] , [[id:cdec3613-5af5-4d6e-844d-f5cee6da31b8][Dr. Richard Schwartz]]

* Overview

Internal Family Systems is a powerfully transformative, evidence-based model of psychotherapy. We believe the mind is naturally multiple and that is a good thing.  Our inner parts contain valuable qualities and our core Self knows how to heal, allowing us to become integrated and whole. In IFS all parts are welcome.

* Parts

Parts are from the past and they carry burdens.

* Burdens

The release of Part Burdens allow the Part to come into it's full self and serve you. To help you.
When you confuse the Burden with the Part, you go to war with the Part. But that's wrong, you're going to war with yourself.

* Resources

[[https://www.soundstrue.com/products/greater-than-the-sum-of-our-parts][Audo series on IFS spiritual journey]] from the creator of IFS, [[id:cdec3613-5af5-4d6e-844d-f5cee6da31b8][Dr. Richard Schwartz]].
