:PROPERTIES:
:ID:       c90eaaf3-9458-4a77-9fc9-6329fd26a062
:END:
#+TITLE: 2021-10-14
#+filetags: Daily

* 01:44:53

Well, my configuration is at a very good place. Home directory configures itself, initializes state, etc. etc. I have conventions for adding new dotfiles and Guix features. And enough documentation to know what the F is going on later. I neeeed to move on.

Next up, working on the standing desk in the office and learning Tailwind + Solidity. Tailwind so I can get the affiliate site off the ground.

* 01:45:59

I also need to start jumping back into my agenda here, and getting a pipeline for Readwise going into my Notebook for content.

Idea. Another store. Show up, and we use GPT-3 to generate review comparisons based on single reviews. You choose a template for how it will look. Look at Wordpress plugin for guidance. Find OTHER Wordpress plugins to port over to the pre-rendered world.


* 12:57:47

** TODO [#B] Fix dryer duct to not have a hole                        :@Home:
** DONE [#A] Pay Corrigan bill
** NEXT [#A] Pay Tesla loan
