:PROPERTIES:
:ID:       9BCB84DF-94B8-46F2-8A76-86A375779A4A
:END:
#+TITLE: 2021-09-01
#+filetags: Daily

* 08:48:58

Notes for Mom's conversation.

1. Father's Day not speaking, you want to leave him, now you don't, goes to the hospital
   Hides drinking a fifth at my house, tells lies, drunk at dinner
   Drunk driving you around, now choosing to drink over Isaiah
   Told me he'd quit for 30 days
   This isn't normal behavior

   I think there is a great person in there, hurt by alcohol, the only way to get it out is to treat this as a medical issue

   Everyone is enabling it, we aren't taking part in it. Lindsay is extremely toxic, sends me hurtful text messages. As long as she continues to tell you you can't leave him, dad doesn't have a problem, I'm not allowed to say he does, I won't be having a relationship with her anymore. 

   I will have a relationship with you, we love you.
   But you have to recognize you're enabling it to. "Can't control" so I'll just submit to it.

   So we can't talk about dad, ever, we can't talk about Lindsay, ever. We can only talk about dad deciding yes to take responsibility and treat this like the medical issue it is.
