:PROPERTIES:
:ID:       3117e6b7-0a3f-4576-a04c-7afa7be27435
:END:
#+TITLE: 2021-08-08
#+filetags: Daily

* 00:42:47

** DONE  Check on Into The Cryptoverse subscription / chat channel

* 13:25:21

** Discovered the history of [[id:8EA04865-94A8-480A-8719-417C67F4355C][Emacs]] cars and cdr cells:

- The names car and cdr derive from the history of Lisp. The original Lisp implementation ran on an IBM 704 computer which divided words into two parts, called the “address” part and the “decrement”; car was an instruction to extract the contents of the address part of a register, and cdr an instruction to extract the contents of the decrement.

- By contrast, “cons cells” are named for the function cons that creates them, which in turn was named for its purpose, the construction of cells

* 20:45:53

** Team Lyons Meeting

- What is this meeting?

  1. Budget - set budget, set categories, review if we're on track
  2. Calendar - Review the week ahead - discuss appointments, reminders, needs, support requests
  3. Trello - Review outstanding tasks / maintenance and rack our brains for adding new things
  4. Make sure we have enough fun things planned

- We spent time reviewing bed frames for our primary bedroom.

** DONE Call [[id:AAAE7DCD-3F10-43D1-85C1-7548686843E0][Allgeier Air]] to replace upstairs air handler for $9000  :#Phone:
