:PROPERTIES:
:ID:       65c48d4b-aeda-4300-ac57-1389659ce374
:END:
#+TITLE: 2021-09-09
#+filetags: Daily

* 14:49:12

Woke up to a text from my sister, they want to send dad to rehab. Makes me happy people are realizing we need to do it.

* 14:59:02

** Conversation with [[id:ed1c2ca3-a8d5-48ec-af12-afb5642729ff][Kayla Brewer]] about my dad.

 Went well, she wants my dad to attend a 30 day program.

* 18:44:10

** Session with [[id:a8290213-3af8-4c76-b6a1-01a7a7af5fe3][Dario Martinez]]

Three reasons people relapse.

 I feel bad.
 I feel social pressure.
 I feel really good.

*** What do I do about the "extremes"?

 Excitement increases, increases... then it peaks.
 I'm really good at getting the idea, being the visionary, really good at increasing and getting the energy going, and then... hit the peak. Then something happens and it's hard to sustain that for a long time.

 At Yancy's, I wanted more of the "check out" feeling after Sweeply didn't go live. I was burned out.

*** How do I fix this?

 Bring intention to what I'm doing. Bring a balance. Don't be on autopilot. I will end up burnt out and tired.

*** Am I headed toward burnout?

 Noticing what's happening. Telling myself -- okay Dustin, I could see this could go south really quickly if I don't take care of myself. If I don't have fun. Spend time with my son. Do joy.

The Four Rooms isn't just for balance, it's also to keep me sober.

*** Am I prioritizing intellutcal vs emotional?

Emotional == engaging. Actually emotional, working with Amanda. Being emotional. Not just doing the activities.

Just stop doing things. Just talk to Amanda. Me connecting with her. Be in the moment, talking about things.

Ask Amanda and understand what I can do to make our relationship better. I'm understanding emotional needs and reacting to them.

*** What is my cycle?

I have passion and it isn't bad, but it can lead to frustration in my relationships, burn out for myself, loss of connectivity with my partner. The rooms are going to be out of balance.

PAY ATTENTION TO EXTREMES. Extremes are always indiciation I'm in a part, and what road is that part going to take me down.
