:PROPERTIES:
:ID:       49290004-a9df-4506-81f2-01b280d5f2ee
:END:
#+TITLE: 2021-11-19
#+filetags: Daily

** 01:43:57

Review [[id:2E154EDA-B357-461B-981E-7D6C2A959382][Create a Daily Schedule]] and [[id:E8B03D08-5BF9-4542-816C-D44FF1D458D7][Life]] projects again.


** 15:04:12

*** [[id:23E5974A-2B42-401E-A6D8-6C5BDD514D83][ScholarRx]] - [[id:BCDD50DD-B059-4B21-BAFE-002D8F75E642][Matt Harris]] and [[id:0658A09E-7BBD-40D2-8FCC-D5A05350B77A][Ashley Dickerson]] meeting

What are schools looking for and why? Wake Forest -- Video report last week. QMax, Bricks. My strategy is let's give them a comprehensive report.

Video report, pulled a report. They said thanks, it was helpful. They did want to see how long they watched -- we can put that info in there, it might be misleading.

How long session in Express Videos? Individual video and how long. What subjects are the students looking at?

Maybe we don't do a good job of teaching. Big picture, gain insights into their own curriculum.

Goal here. Express video build w/ QMax, Will show them report after Thanksgiving. Takeaways -- Dustin to explore QMax, Express Videos in addition to Bricks.


** 16:23:03
