:PROPERTIES:
:ID:       BA688D14-5965-41B5-B990-D03898AF0684
:END:
#+TITLE: 2021-09-23
#+filetags: Daily

* 18:16:19

[[id:a8290213-3af8-4c76-b6a1-01a7a7af5fe3][Dario Martinez]] session.

Being critical becomes a problem, because it is happening all the time
Younger part was told he had to be great, this is just a part. It's a kid inside of me where things had to be perfect.

Many unknowns -- house, new business, family. When there are a lot of unknowns, parts of us try to exhert control. This is how we find safety.

Remember ---- this is a part of me. When it's happening all the time, remember the part is scared and he's a young kid. Anxious, nervous older version. Younger version just wants to be great, older person just wants it to happen.

Help that part see if there is another way, to find a sense of safety. Have choice around it, and recognize when to back up,.

First. Notice the part. Then talk to it. Is the battle I want to fight? Bring awareness to the part.

Feeling grief. It makes a lot of sense controling part is online. Grief is about loss. My family system has problems and they are not willing to fix it, I have no control. I have no control over how they react to me.

Sit with it, get to know it.
